[package]
name = "beautiful_inno_bot"
version = "0.3.3"
edition = "2021"

[profile.release]
lto = "fat"
strip = "debuginfo"
opt-level = "z"
panic = "abort"
codegen-units = 1

[dependencies]
Inflector = "0.11"
anyhow = "1.0"
dotenv = "0.15"
envconfig = "0.10"
image = "0.25"
kamadak-exif = "0.5"
log = "0.4"
mime = "0.3"
pretty_env_logger = "0.5"
regex = "1.10"
sentry = "0.34"
teloxide = { version = "0.12", features = ["macros"] }
tokio = { version = "1.0", features = ["rt", "rt-multi-thread", "macros"] }
uuid = "1.7"
