services:
  postgres:
    image: postgres:14-alpine
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      POSTGRES_USER: bot
      POSTGRES_DB: bot
      POSTGRES_PASSWORD: pass_bot
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bot" ]
      interval: 2s
      timeout: 2s
      retries: 5

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 5

  bot:
    build:
      dockerfile: "./Dockerfile"
      context: .
    command: sh -c "cargo run --profile docker -- --start"
    #command: sh -c "tail -f /dev/null"
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  pg_data:
  redis_data: