FROM rust:alpine AS builder

ENV RUSTFLAGS="-C target-feature=-crt-static"

WORKDIR /app

COPY . /app

RUN apk --no-cache add pkgconfig musl-dev openssl-dev clang-dev build-base make libheif-dev libpq-dev \
    && rm -rf /var/cache/apk/*

RUN cargo build --release

FROM alpine:edge

ARG BOT_VERSION=unknown
ENV BOT_VERSION=$BOT_VERSION

LABEL org.opencontainers.image.base.name="alpine:edge"

COPY --from=builder /app/target/release/beautiful_inno_bot /usr/local/bin/beautiful_inno_bot
COPY ./locales/ /app

RUN apk --no-cache add ca-certificates openssl libgcc libstdc++ libheif libheif-tools libpq \
    && rm -rf /var/cache/apk/*

CMD ["beautiful_inno_bot"]
